# Generated by Django 3.2.7 on 2021-10-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211027_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationstoserver',
            old_name='server_id',
            new_name='server_name',
        ),
    ]
