# Generated by Django 3.2.7 on 2021-10-15 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210921_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField()),
                ('server_name', models.CharField(max_length=100)),
                ('server_picture', models.ImageField(blank=True, upload_to='')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servers')),
                ('users_online', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
