# Generated by Django 3.2.7 on 2021-10-19 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_joinserverrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinserverrequests',
            name='response',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(2)]),
        ),
    ]
