# Generated by Django 3.2.7 on 2021-11-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211110_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pictures/default-pic.png', upload_to='pictures'),
        ),
    ]
