# Generated by Django 3.2.7 on 2021-10-21 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_joinserverrequests_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinserverrequests',
            name='response',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.CreateModel(
            name='InvitationsToServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('response', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servers')),
                ('user_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
